
import type { Station } from '@/types';
import placeholders from '@/app/lib/placeholder-images.json';

export const stations: Station[] = [
  { id: 's9', name: 'AIR Kolkata', streamUrl: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio165/playlist.m3u8', logoUrl: placeholders.air_kolkata_logo, category: 'news' },
  { id: 's10', name: 'Vividh Bharati', streamUrl: 'https://radio.wavespb.com/live/146ed6ec6dea5a24/146ed6ec6dea5a24.m3u8', logoUrl: placeholders.vividh_bharati_logo, category: 'music' },
  { id: 's11', name: 'AIR FM Gold (Kolkata)', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio057/hlspbaudio05764kbps.m3u8', logoUrl: placeholders.air_fm_gold_logo, category: 'music' },
  { id: 's12', name: 'AIR Murshidabad', streamUrl: 'https://d1cvqgmbcpg5yn.cloudfront.net/47a45f818dd9203b/47a45f818dd9203b.m3u8', logoUrl: placeholders.murshidabad_logo, category: 'news' },
  { id: 's13', name: 'Air Rainbow 107 Kolkata', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio058/hlspbaudio05864kbps.m3u8', logoUrl: placeholders.air_rainbow_logo, category: 'music' },
  { id: 's14', name: 'Kolkata - Geetanjali', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio055/hlspbaudio05564kbps.m3u8', logoUrl: placeholders.kolkata_geetanjali_logo, category: 'bangla_music' },
  { id: 's15', name: 'All India Radio News 24X7', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio233/hlspbaudio23364kbps.m3u8', logoUrl: placeholders.air_news_logo, category: 'news' },
  { id: 's16', name: 'Akashvani Kolkata Sanchayita', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio056/hlspbaudio05664kbps.m3u8', logoUrl: placeholders.sanchayita_logo, category: 'music' },
  { id: 's17', name: 'Akashvani Maitree', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio245/hlspbaudio24564kbps.m3u8', logoUrl: placeholders.maitree_logo, category: 'news' },
  { id: 's18', name: 'Akashvani Shantiniketan', streamUrl: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio247/playlist.m3u8', logoUrl: placeholders.shantiniketan_logo, category: 'music' },
  { id: 's19', name: 'Mirchi 98.3 FM', streamUrl: 'https://eu8.fastcast4u.com/proxy/clyedupq?mp=%2F1?aw_0_req_lsid=2c0fae177108c9a42a7cf24878625444', logoUrl: placeholders.radio_mirchi_983_logo, category: 'bangla_music' },
  { id: 's23', name: 'Radio Mirchi Kolkata', streamUrl: 'https://19013.live.streamtheworld.com/NJS_HIN_EST_SC', logoUrl: 'https://api.iconify.design/emojione/hot-pepper.svg', category: 'bangla_music' },
  { id: 's21', name: 'Air FM Gold', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio005/hlspbaudio00564kbps.m3u8', logoUrl: placeholders.air_fm_gold_national_logo, category: 'music' },
  { id: 's22', name: 'Air FM Rainbow', streamUrl: 'https://airhlspush.pc.cdn.bitgravity.com/httppush/hlspbaudio004/hlspbaudio00464kbps.m3u8', logoUrl: placeholders.air_fm_rainbow_national_logo, category: 'music' },
  { id: 's26', name: 'Radio City Bangalore 91.1 FM', streamUrl: 'https://a2.asurahosting.com/hls/office_radio/live.m3u8', logoUrl: 'https://api.iconify.design/emojione/radio.svg', category: 'music' },
  { id: 's27', name: 'Red FM', streamUrl: 'https://stream-175.zeno.fm/q97eczydqrhvv', logoUrl: placeholders.red_fm_logo, category: 'music' },
  { id: 's28', name: 'Big FM 92.7 Delhi', streamUrl: 'https://stream-152.zeno.fm/dbstwo3dvhhtv', logoUrl: placeholders.big_fm_logo, category: 'music' },
  { id: 's29', name: 'Uttorbango Betar', streamUrl: 'https://stream.zeno.fm/vdrtn8ffgrruv', logoUrl: placeholders.uttorbango_betar_logo, category: 'news' },
  { id: 's30', name: 'Spice FM 96.4', streamUrl: 'https://stream.spicefmbd.com/stream.m3u8', logoUrl: placeholders.spice_fm_logo, category: 'music' },
  { id: 's31', name: 'Bollywood Classic Songs', streamUrl: 'http://node-12.zeno.fm/60ef4p33vxquv?rj-ttl=5&rj-tok=AAABc-OCFngAs_AvDsY_StEpMg', logoUrl: placeholders.bollywood_classic_logo, category: 'music' },
  { id: 's32', name: 'Akashvani Siliguri', streamUrl: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio164/chunklist.m3u8', logoUrl: placeholders.akashvani_siliguri_logo, category: 'news' },
  { id: 's33', name: 'Bollywood 2010s', streamUrl: 'https://3.mystreaming.net/uber/bollywood2010s/icecast.audio', logoUrl: placeholders.bollywood_2010s_logo, category: 'music' },
  { id: 's34', name: 'Bollywood 2000s', streamUrl: 'https://nl4.mystreaming.net/uber/bollywood2000s/icecast.audio', logoUrl: placeholders.bollywood_2000s_logo, category: 'music' },
  { id: 's35', name: 'Bollywood 1990s', streamUrl: 'https://nl4.mystreaming.net/uber/bollywood1990s/icecast.audio', logoUrl: placeholders.bollywood_1990s_logo, category: 'music' },
  { id: 's36', name: 'Best FM', streamUrl: 'https://radio.mbconline.xyz/hls/bestfm.m3u8', logoUrl: placeholders.best_fm_logo, category: 'music' },
  { id: 's37', name: 'Bhakti Sangeet', streamUrl: 'https://node-20.zeno.fm/ut3kgm1vsa0uv?1755076507', logoUrl: placeholders.bhakti_sangeet_logo, category: 'bhakti' },
  { id: 's38', name: 'Radio Dil', streamUrl: 'https://us3.streamingpulse.com/ssl/radiodil2', logoUrl: placeholders.radio_dil_logo, category: 'music' },
  { id: 's39', name: 'Bollywood Dance', streamUrl: 'https://3.mystreaming.net/uber/bollywooddance/icecast.audio', logoUrl: placeholders.bollywood_dance_logo, category: 'music' },
  { id: 's40', name: 'Bollywood Work Out', streamUrl: 'https://nl4.mystreaming.net/uber/bollywoodworkout/icecast.audio', logoUrl: placeholders.bollywood_workout_logo, category: 'music' },
  { id: 's41', name: 'Bollywood Gold', streamUrl: 'https://3.mystreaming.net/uber/bollywoodgold/icecast.audio', logoUrl: placeholders.bollywood_gold_logo, category: 'music' },
  { id: 's42', name: 'Bollywood Love', streamUrl: 'https://3.mystreaming.net/uber/bollywoodlove/icecast.audio', logoUrl: placeholders.bollywood_love_logo, category: 'music' },
  { id: 's43', name: 'Bollywood Mix', streamUrl: 'https://3.mystreaming.net/uber/bollywoodmix/icecast.audio', logoUrl: placeholders.bollywood_mix_logo, category: 'music' },
  { id: 's44', name: 'Bollywood Now', streamUrl: 'https://3.mystreaming.net/uber/bollywoodnow/icecast.audio', logoUrl: placeholders.bollywood_now_logo, category: 'music' },
  { id: 's45', name: 'Radio BollyFM', streamUrl: 'https://antares.dribbcast.com/proxy/radiobolly/stream.mp3', logoUrl: placeholders.radio_bollyfm_logo, category: 'music' },
  { id: 's46', name: 'Radio Mirchi 98.3', streamUrl: 'https://listen.openstream.co/4603/audio', logoUrl: 'https://api.iconify.design/emojione/hot-pepper.svg', category: 'music' },
  { id: 's47', name: 'Radio Nasha 91.9', streamUrl: 'https://stream-157.zeno.fm/zu59ykebs2zuv', logoUrl: placeholders.radio_nasha_logo, category: 'music' },
  { id: 's48', name: 'Mirchi Love 104 FM', streamUrl: 'https://drive.uber.radio/uber/lrbollywood/icecast.audio', logoUrl: placeholders.mirchi_love_logo, category: 'music' },
  { id: 's49', name: 'East FM', streamUrl: 'https://eastfm-atunwadigital.streamguys1.com/eastfm', logoUrl: placeholders.east_fm_logo, category: 'music' },
  { id: 's50', name: 'ISHQ 104.8 FM', streamUrl: 'https://3.mystreaming.net/uber/bollywoodlove/icecast.audio', logoUrl: placeholders.ishq_fm_logo, category: 'music' },
  { id: 's51', name: 'Radio Wow', streamUrl: 'https://stream-175.zeno.fm/d22wrdbst5quv', logoUrl: placeholders.radio_wow_logo, category: 'music' },
  { id: 's52', name: 'Kadak FM', streamUrl: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio099/playlist.m3u8', logoUrl: 'https://api.iconify.design/emojione/radio.svg', category: 'music' },
  { id: 's53', name: 'Arijit Singh Hindi', streamUrl: 'https://nl4.mystreaming.net/uber/bollywoodarijitsingh/icecast.audio', logoUrl: placeholders.arijit_singh_hindi_logo, category: 'music', artist: 'Arijit Singh' },
  { id: 's54', name: 'Madhur Sangeet', streamUrl: 'https://stream-163.zeno.fm/8kqd6dp18vzuv', logoUrl: placeholders.madhur_sangeet_logo, category: 'music' },
  { id: 's55', name: 'Radio Quarantine Kolkata', streamUrl: 'https://stream-179.zeno.fm/tkdbd3bxk2zuv', logoUrl: placeholders.radio_quarantine_logo, category: 'news' },
  { id: 's56', name: 'Aaj Tak', streamUrl: 'https://aajtaklive-amd.akamaized.net/hls/live/2014416/aajtak/aajtaklive/live_234p/chunks.m3u8', logoUrl: placeholders.aaj_tak_logo, category: 'news' },
  { id: 's57', name: 'Lyca Radio', streamUrl: 'https://ads-direct.sharp-stream.com/1458.mp3', logoUrl: placeholders.lyca_radio_logo, category: 'music' },
  { id: 's58', name: 'Live Cricket Commentary', streamUrl: 'https://strw3.openstream.co/399?aw_0_1st.collectionid%3D6983%26stationId%3D6983%26publisherId%3D219%26k%3D1750184609/;stream/1', logoUrl: placeholders.cricket_commentary_logo, category: 'news' },
  { id: 's59', name: 'Radio Badal', streamUrl: 'https://stream-146.zeno.fm/nhrtcxg09u8uv', logoUrl: placeholders.radio_badal_logo, category: 'music' },
  { id: 's60', name: 'Bhaktiworld Media Shri Ram', streamUrl: 'https://dard.out.airtime.pro/dard_a', logoUrl: placeholders.bhaktiworld_shri_ram_logo, category: 'bhakti' },
  { id: 's61', name: 'Bhaktiworld Media Krishna', streamUrl: 'https://millenniumhits.out.airtime.pro:8000/millenniumhits_a', logoUrl: placeholders.bhaktiworld_krishna_logo, category: 'bhakti' },
  { id: 's62', name: 'Bhaktiworld Media Shiva', streamUrl: 'https://hot.out.airtime.pro/hot_a', logoUrl: placeholders.bhaktiworld_shiva_logo, category: 'bhakti' },
  { id: 's63', name: 'Bhaktiworld Media Ganesha', streamUrl: 'https://radio2bindia.out.airtime.pro/radio2bindia_a', logoUrl: placeholders.bhaktiworld_ganesha_logo, category: 'bhakti' },
  { id: 's64', name: 'Bhaktiworld Media Devi Maa', streamUrl: 'https://ibadat.out.airtime.pro/ibadat_a', logoUrl: placeholders.bhaktiworld_devi_maa_logo, category: 'bhakti' },
  { id: 's65', name: 'Bhaktiworld Media Hanuman Ji', streamUrl: 'https://2bhanuman.out.airtime.pro:8000/2bhanuman_a', logoUrl: placeholders.bhaktiworld_hanuman_logo, category: 'bhakti' },
  { id: 's66', name: 'Mantra Shakti', streamUrl: 'https://djbeat.out.airtime.pro:8000/djbeat_a', logoUrl: placeholders.mantra_shakti_logo, category: 'bhakti' },
  { id: 's67', name: 'BIG FM 92.7 Mumbai', streamUrl: 'https://node-15.zeno.fm/e7nuzpte6qruv', logoUrl: placeholders.big_fm_mumbai_logo, category: 'music' },
  { id: 's68', name: 'Mixify', streamUrl: 'https://server.mixify.in/listen/listen/radio.mp3', logoUrl: placeholders.mixify_logo, category: 'music' },
  { id: 's69', name: 'Radio BollyFM', streamUrl: 'https://antares.dribbcast.com/proxy/radiobolly/stream.mp3', logoUrl: placeholders.radio_bollyfm_logo, category: 'music' },
  { id: 's70', name: 'Mixify Bengali Hits', streamUrl: 'https://server.mixify.in/listen/bangla/radio.mp3', logoUrl: placeholders.mixify_bengali_hits_logo, category: 'bangla_music' },
  { id: 's71', name: 'Geet Radio 24/7 Bangla Music', streamUrl: 'https://server.geetradio.com:8050/radio.mp3', logoUrl: 'https://api.iconify.design/emojione/musical-score.svg', category: 'bangla_music' },
  { id: 's72', name: 'Marwar Radio', streamUrl: 'https://stream-161.zeno.fm/vq6p5vxb4v8uv', logoUrl: placeholders.marwar_radio_logo, category: 'music' },
  { id: 's73', name: '103 FM India', streamUrl: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio099/chunklist.m3u8', logoUrl: 'https://api.iconify.design/emojione/radio.svg', category: 'music' },
  { id: 's74', name: 'Radio Hulchul', streamUrl: 'https://everestcast.live-streams.nl:18015/stream', logoUrl: placeholders.radio_hulchul_logo, category: 'music' },
  { id: 's75', name: 'Radio Olive', streamUrl: 'https://27943.live.streamtheworld.com/OLIVE1063.mp3', logoUrl: placeholders.radio_olive_logo, category: 'music' },
  { id: 's76', name: 'Radio Baingan', streamUrl: 'https://stream-165.zeno.fm/eyxg23ky4x8uv', logoUrl: placeholders.radio_baingan_logo, category: 'music' },
  { id: 's77', name: 'Radio Namkin', streamUrl: 'https://stream-152.zeno.fm/84h7fsbaqv5tv', logoUrl: placeholders.radio_namkin_logo, category: 'music' },
  { id: 's78', name: 'My Radio DJ online', streamUrl: 'https://stream-152.zeno.fm/84h97t3ewg0uv', logoUrl: placeholders.my_radio_dj_logo, category: 'music' },
  { id: 's79', name: 'New Hits Of Bollywood', streamUrl: 'https://stream-165.zeno.fm/rqqps6cbe3quv', logoUrl: placeholders.new_hits_bollywood_logo, category: 'music' },
  { id: 's80', name: 'Hungama Radio - Bhakti Saagar', streamUrl: 'https://stream-142.zeno.fm/syu0rdutvxhvv', logoUrl: 'https://api.iconify.design/emojione/folded-hands.svg', category: 'bhakti' },
  { id: 's81', name: 'Radio Bangla net', streamUrl: 'https://18213.live.streamtheworld.com/SP_R3563475_SC', logoUrl: placeholders.radio_bangla_net_logo, category: 'bangla_music' },
  { id: 's82', name: 'Hot Now Bangla', streamUrl: 'https://stream.radiotreetal.com/listen', logoUrl: placeholders.hot_now_bangla_logo, category: 'bangla_music' },
  { id: 's83', name: 'Lata Mangeshkar Radio', streamUrl: 'https://stream-160.zeno.fm/87xam8pf7tzuv', logoUrl: placeholders.lata_mangeshkar_logo, category: 'music', artist: 'Lata Mangeshkar' },
  { id: 's84', name: 'Kumar Sanu Radio', streamUrl: 'https://stream-160.zeno.fm/shxt7qxapy8uv', logoUrl: placeholders.kumar_sanu_logo, category: 'music', artist: 'Kumar Sanu' },
  { id: 's85', name: 'Alka Yagnik Radio', streamUrl: 'https://nl4.mystreaming.net/uber/bollywoodalkayagnik/icecast.audio', logoUrl: placeholders.alka_yagnik_logo, category: 'music', artist: 'Alka Yagnik' },
  { id: 's86', name: 'Kalighat Radio', streamUrl: 'https://stream-167.zeno.fm/60ef4p33vxquv', logoUrl: placeholders.kalighat_radio_logo, category: 'bangla_music' },
  { id: 's87', name: 'Hungama Bollywood Dil Se', streamUrl: 'https://stream-157.zeno.fm/143d7gty24zuv', logoUrl: placeholders.hungama_bollywood_dil_se_logo, category: 'music' },
  { id: 's88', name: 'Bhaktisudha Radio', streamUrl: 'https://n09.radiojar.com/cfqyfcspcv8uv?rj-ttl=5&rj-tok=AAABm7MSxAwArgFBqK5_v-yk-g', logoUrl: placeholders.bhaktisudha_radio_logo, category: 'bhakti' },
  { id: 's89', name: 'Radio Aashiqanaa', streamUrl: 'https://mars.streamerr.co/8154/stream', logoUrl: 'https://api.iconify.design/emojione/red-heart.svg', category: 'music' },
  { id: 's90', name: 'Mirchi Hindi Retro', streamUrl: 'https://stream-148.zeno.fm/v2zfmxef798uv', logoUrl: placeholders.mirchi_hindi_retro_logo, category: 'music' },
  { id: 's91', name: 'Namaste Bollywood', streamUrl: 'https://stream-167.zeno.fm/cqak4ap7by8uv', logoUrl: placeholders.namaste_bollywood_logo, category: 'music' },
  { id: 's92', name: 'Hindvani Fm', streamUrl: 'https://edge.iono.fm/xice/129_medium.aac', logoUrl: placeholders.hindvani_fm_logo, category: 'music' },
  { id: 's93', name: 'Old Monk Radio', streamUrl: 'https://stream-165.zeno.fm/pr0zc64zdy8uv', logoUrl: placeholders.old_monk_radio_logo, category: 'music' },
  { id: 's94', name: 'Sunrise Radio', streamUrl: 'https://stream1.themediasite.co.uk/8070/high', logoUrl: placeholders.sunrise_radio_logo, category: 'music' },
  { id: 's95', name: 'Radio Jagriti 90.4 FM', streamUrl: 'https://stream-154.zeno.fm/4dycn4hmffhvv', logoUrl: placeholders.radio_jagriti_logo, category: 'news' },
  { id: 's96', name: 'Agra Radio', streamUrl: 'https://stream-160.zeno.fm/m1krtxpk11zuv', logoUrl: placeholders.agra_radio_logo, category: 'music' },
  { id: 's97', name: 'Instrumental Music Radio', streamUrl: 'https://azuracast.vibesounds.in:8030/radio.mp3', logoUrl: placeholders.instrumental_music_radio_logo, category: 'music' },
  { id: 's98', name: 'Bombay Beats', streamUrl: 'https://strmreg.1.fm/bombaybeats_mobile_mp3', logoUrl: placeholders.bombay_beats_logo, category: 'music' },
  { id: 's99', name: 'Shreya Ghosal Radio', streamUrl: 'https://nl4.mystreaming.net/uber/bollywoodshreyaghosal/icecast.audio', logoUrl: placeholders.shreya_ghosal_logo, category: 'music', artist: 'Shreya Ghoshal' },
  { id: 's100', name: 'Bollywood Shah Rukh Khan', streamUrl: 'https://3.mystreaming.net/uber/bollywoodshahrukhkhan/icecast.audio', logoUrl: placeholders.shah_rukh_khan_logo, category: 'music', artist: 'Shah Rukh Khan' },
  { id: 's101', name: 'Hare Krsna Radio', streamUrl: 'https://cast5.asurahosting.com/proxy/harekrsn/stream', logoUrl: placeholders.hare_krsna_logo, category: 'bhakti' },
  { id: 's102', name: 'Mixify Hindi Hits', streamUrl: 'https://server.mixify.in/listen/new_hits/radio.mp3', logoUrl: placeholders.mixify_hindi_hits_logo, category: 'music' },
  { id: 's103', name: 'Radio Sangam', streamUrl: 'https://streaming.radio.co/s58948a3f0/listen', logoUrl: placeholders.radio_sangam_logo, category: 'music' },
  { id: 's104', name: 'Bollywood Diwali Party', streamUrl: 'https://nl4.mystreaming.net/uber/bollywooddiwali/icecast.audio', logoUrl: placeholders.bollywood_diwali_logo, category: 'music' },
  { id: 's105', name: 'Nostalgic Bollywood 90s', streamUrl: 'https://www.desizoneradio.com/relay3', logoUrl: placeholders.nostalgic_bollywood_90s_logo, category: 'music' },
  { id: 's106', name: 'Diverse FM', streamUrl: 'https://carol.epichosts.co.uk:8570/;', logoUrl: placeholders.diverse_fm_logo, category: 'music' },
  { id: 's107', name: 'Bolly 102.9 FM', streamUrl: 'https://ice6.securenetsystems.net/INTRADIO?type=.mp3', logoUrl: placeholders.bolly_102_9_fm_logo, category: 'music' },
  { id: 's108', name: 'Filmy Mirchi', streamUrl: 'https://streaming.webhostnepal.com/8020/stream', logoUrl: placeholders.filmy_mirchi_logo, category: 'music' },
  { id: 's109', name: 'Udit Narayan', streamUrl: 'https://3.mystreaming.net/uber-app/bollywooduditnarayan/icecast.audio', logoUrl: placeholders.udit_narayan_logo, category: 'music', artist: 'Udit Narayan' },
  { id: 's110', name: 'Hindi Filmy Songs', streamUrl: 'https://streaming.webhostnepal.com/8020/stream', logoUrl: placeholders.hindi_filmy_songs_logo, category: 'music' },
  { id: 's111', name: 'Mohabbat Radio', streamUrl: 'https://stream-140.zeno.fm/u7dyh8zsgtzuv', logoUrl: placeholders.mohabbat_radio_logo, category: 'music' },
  { id: 's112', name: 'Himesh Reshammiya', streamUrl: 'https://stream-158.zeno.fm/wg53ebxp8hhvv', logoUrl: placeholders.himesh_reshammiya_logo, category: 'music', artist: 'Himesh Reshammiya' },
  { id: 's113', name: 'Drive Radio', streamUrl: 'https://stream-177.zeno.fm/tn4spkm3dy8uv', logoUrl: 'https://api.iconify.design/emojione/automobile.svg', category: 'music' },
  { id: 's114', name: 'Arijit Singh Hits', streamUrl: 'https://stream-158.zeno.fm/rfpf8qec94zuv', logoUrl: placeholders.arijit_singh_hits_logo, category: 'music', artist: 'Arijit Singh' },
  { id: 's115', name: 'Himal Radio Hindi Filmy', streamUrl: 'https://streaming.webhostnepal.com/8020/stream', logoUrl: placeholders.himal_radio_hindi_filmy_logo, category: 'music' },
  { id: 's116', name: 'Kishore Kumar Radio', streamUrl: 'https://stream-166.zeno.fm/0ghtfp8ztm0uv', logoUrl: placeholders.kishore_kumar_logo, category: 'music', artist: 'Kishore Kumar' },
  { id: 's117', name: 'Lyca Radio Gold', streamUrl: 'https://listen-lycaradio.sharp-stream.com/1035.mp3', logoUrl: placeholders.lyca_radio_gold_updated_logo, category: 'music' },
  { id: 's118', name: 'Radio Active 90.4 FM', streamUrl: 'https://stream-157.zeno.fm/xwhhyc5nyk8uv', logoUrl: placeholders.radio_active_90_4_fm_logo, category: 'news' },
  { id: 's119', name: 'Radio 90.5 FM', streamUrl: 'https://ice42.securenetsystems.net/CR90', logoUrl: placeholders.radio_90_5_fm_logo, category: 'music' },
  { id: 's120', name: 'MY CLUB REMIX', streamUrl: 'https://stream-160.zeno.fm/pkvh8zhyzp8uv', logoUrl: placeholders.my_club_remix_logo, category: 'music' },
  { id: 's121', name: 'My 90s Bengali', streamUrl: 'https://stream-154.zeno.fm/9bze9t1pvs8uv', logoUrl: placeholders.my_90s_bengali_logo, category: 'bangla_music' },
  { id: 's122', name: 'FnF.FM online', streamUrl: 'https://eu6.fastcast4u.com/proxy/arrahm00?mp=/1', logoUrl: placeholders.fnf_fm_online_logo, category: 'music' },
  { id: 's124', name: 'Radio Theater Bangla', streamUrl: 'https://stream-151.zeno.fm/hrawdb5yx8ovv', logoUrl: placeholders.radio_theater_bangla_logo, category: 'bangla_music' },
  { id: 's125', name: 'Radio Malda', streamUrl: 'https://stream-175.zeno.fm/10rt7tpf6ehvv', logoUrl: placeholders.radio_malda_logo, category: 'news' },
  { id: 's126', name: 'Radio High 92.7', streamUrl: 'https://stream-177.zeno.fm/89zztr1dec9uv', logoUrl: placeholders.radio_high_92_7_logo, category: 'music' },
  { id: 's127', name: 'Radio Milan 90.4', streamUrl: 'https://stream-175.zeno.fm/io4zzsy1ndbvv', logoUrl: 'https://api.iconify.design/emojione/radio.svg', category: 'music' },
  { id: 's128', name: 'Radio Vivid Voice', streamUrl: 'https://stream-152.zeno.fm/xuin6ocdc2juv', logoUrl: placeholders.radio_vivid_voice_logo, category: 'music' },
  { id: 's129', name: 'Ankora Radio', streamUrl: 'https://stream-175.zeno.fm/xush70b1cbruv', logoUrl: placeholders.ankora_radio_logo, category: 'bangla_music' },
  { id: 's130', name: 'Kolkata FM', streamUrl: 'https://stream-177.zeno.fm/8rx9t0gfps8uv', logoUrl: placeholders.kolkata_fm_logo, category: 'bangla_music' },
  { id: 's131', name: 'Radio Moonlight', streamUrl: 'https://stream-178.zeno.fm/6tvvetnnhzzuv', logoUrl: placeholders.radio_moonlight_logo, category: 'music' }
];
